baseurl: /color
host: 0.0.0.0
markdown: kramdown
highlighter: rouge

oc-version: 0.1.0
colors: [
                  "gray",
                  "red",
                  "purple",
                  "blue",
                  "green",
                  "yellow"
]

gray-hexs: [
                  "#F7FAFC",
                  "#EBF1F9",
                  "#E0E9F5",
                  "#CEDDEF",
                  "#B7C3D1",
                  "#9BA6B3",
                  "#676F78",
                  "#4D535A",
                  "#34383C"
]

red-hexs: [
                  "#E9503C"
]

purple-hexs: [
                  "#8621D0"
]

blue-hexs: [
                  "#1B99FF"
]

green-hexs: [
                  "#45D016"
]

yellow-hexs: [
                  "#FFC928"
]

